pipeline:
  identifier: Build_sunkickr_research_assistant_1778795580147
  name: Build research-assistant
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1778795492909
        repoName: sunkickr/research-assistant
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install --upgrade pip
                      python3 -m pip install -r requirements.txt -v
                      python3 -m pip install -e .
                  timeout: "3m"
                  type: Run
              - step:
                  type: Run
                  name: tests
                  identifier: tests
                  spec:
                    shell: Sh
                    command: pytest -v
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
